name: CI - auto finance personal tracker

on:
  push:
    branches: ['main', 'feature/*']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyflakes

      - name: Lint with pyflakes
        run: |
          source venv/bin/activate
          pyflakes app || true

      - name: Syntax check (import test)
        run: |
          source venv/bin/activate
          python -m compileall app

      - name: Write Google credentials to file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > $GITHUB_WORKSPACE/credentials.json
        
      - name: Run basic FastAPI startup test
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          source venv/bin/activate
          cd ${{ github.workspace }}
          python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          SERVER_PID=$!
          sleep 5
          curl -f http://127.0.0.1:8000/ || echo "Server test failed"
          kill $SERVER_PID || true